# Brainsmith Project Settings

# Build directory for compilation artifacts
build_dir: ${HOME}/.brainsmith_build

# Xilinx tool configuration
xilinx_path: /tools/Xilinx
xilinx_version: "2024.2"

# Debug settings
plugins_strict: true
debug: false