name: "cybsec_test"
clock_ns: 10.0
output: "estimates"
board: "RFSoC2x2"
save_intermediate_models: true
parallel_builds: 1
finn_config:
  target_fps: 1000000
  mvau_wwidth_max: 80
design_space:
  kernels:
    - Thresholding
    - MVAU
  steps:
    - finn:qonnx_to_finn # happens even when I remove this line
    - "tidy_up"
    - "streamline"
    - "convert_to_hw"