name: Docker Image CI

on:
  push:
    branches: [ "develop", "ci-actions" ]
  pull_request:
    branches: [ "develop", "ci-actions" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: ./run-docker.sh

