name: Release

on:
  release:
    types: [published]

env:
  DOCKER_BUILDKIT: 1
  BSMITH_DOCKER_PREBUILT: "0"
  BSMITH_DOCKER_NO_CACHE: "1"
  BSMITH_SKIP_DEP_REPOS: "0"
  BSMITH_XILINX_VERSION: ${{ vars.BSMITH_XILINX_VERSION }}
  BSMITH_XILINX_PATH: ${{ vars.BSMITH_XILINX_PATH }}
  NUM_DEFAULT_WORKERS: ${{ vars.NUM_DEFAULT_WORKERS }}
  BSMITH_DOCKER_TAG: "microsoft/brainsmith:${{ github.event.release.tag_name }}"
  BSMITH_DOCKER_FLAGS: "-e XILINXD_LICENSE_FILE=${{ secrets.XILINXD_LICENSE_FILE }} --label ci-run=${{ github.run_id }}"

permissions:
  contents: read
  packages: write

jobs:
  release-image:
    uses: ./.github/workflows/build-and-push.yml
    with:
      runner: 'pre-release'
      test-image: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  
  push-to-ghcr:
    needs: release-image
    runs-on: pre-release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Load Docker image
        uses: ./.github/actions/docker-load
        with:
          artifact-name: brainsmith-image
          image-tag: ${{ env.BSMITH_DOCKER_TAG }}
      
      - name: Push to GHCR
        uses: ./.github/actions/docker-push-release
        with:
          local-tag: ${{ env.BSMITH_DOCKER_TAG }}
          release-tag: ${{ github.event.release.tag_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}